# Generated by Django 4.1.7 on 2023-03-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={
                "ordering": ("user",),
                "verbose_name": "корзина",
                "verbose_name_plural": "корзина",
            },
        ),
        migrations.AlterModelOptions(
            name="favorite",
            options={
                "ordering": ("user",),
                "verbose_name": "избранное",
                "verbose_name_plural": "избранное",
            },
        ),
        migrations.AlterModelOptions(
            name="follow",
            options={
                "ordering": ("author",),
                "verbose_name": "подписка на пользователя",
                "verbose_name_plural": "подписки на пользователей",
            },
        ),
        migrations.AlterModelOptions(
            name="ingredient",
            options={
                "ordering": ("name",),
                "verbose_name": "ингредиент",
                "verbose_name_plural": "ингредиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="ingredientquantity",
            options={
                "ordering": ("recipe",),
                "verbose_name": "кол-во ингредиентов",
                "verbose_name_plural": "кол-во ингредиентов",
            },
        ),
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "ordering": ("name",),
                "verbose_name": "рецепт",
                "verbose_name_plural": "рецепты",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ("name",),
                "verbose_name": "тэг",
                "verbose_name_plural": "тэги",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("username",),
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.UniqueConstraint(
                fields=("follower", "author"), name="follower_author_constraint"
            ),
        ),
    ]
