# Generated by Django 4.1.7 on 2023-03-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_cart_options_alter_favorite_options_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                fields=("user", "recipe"), name="user_recipe_constraint"
            ),
        ),
    ]
