# Generated by Django 4.1.7 on 2023-03-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_cart_user_recipe_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Пользователь"
            ),
        ),
    ]
