# Generated by Django 4.1.7 on 2023-03-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientquantity",
            name="amount",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AddConstraint(
            model_name="ingredientquantity",
            constraint=models.UniqueConstraint(
                fields=("recipe", "ingredient"), name="recipe_ingredient_constraint"
            ),
        ),
    ]
