# Generated by Django 4.1.7 on 2023-03-20 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_recipe_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="description",
            new_name="text",
        ),
    ]
