# Generated by Django 4.1.7 on 2023-03-28 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_ingredientquantity_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientquantity",
            name="amount",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Мин. количество ингридиентов 1"
                    )
                ]
            ),
        ),
    ]
