# Generated by Django 4.1.7 on 2023-03-20 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_rename_description_recipe_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="measure_unit",
            new_name="measurement_unit",
        ),
    ]
