# Generated by Django 4.1.7 on 2023-03-28 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_ingredientquantity_ingredient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientquantity",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredients",
                to="api.ingredient",
            ),
        ),
        migrations.AlterField(
            model_name="ingredientquantity",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes",
                to="api.recipe",
            ),
        ),
    ]
