# Generated by Django 4.1.7 on 2023-03-20 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_ingredientquantity_ingredient_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredientquantity",
            old_name="quantity",
            new_name="amount",
        ),
    ]
