# Generated by Django 4.1.7 on 2023-03-30 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_cart_recipe_alter_cart_user_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together=set(),
        ),
    ]
