# Generated by Django 4.1.7 on 2023-03-22 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_cart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="recipe_in_cart",
            new_name="recipe",
        ),
    ]
