# Generated by Django 4.1.7 on 2023-03-22 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_rename_recipe_in_cart_cart_recipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes_cart",
                to="api.recipe",
            ),
        ),
    ]
